#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="$HOME/.config/hypr/monitors.conf"
TMP_FILE="${CONFIG_FILE}.tmp"

mkdir -p "$(dirname "$CONFIG_FILE")"

if ! command -v hyprctl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
  cat >"$TMP_FILE" <<'EOF'
monitor = ,preferred,auto,1
EOF
  mv "$TMP_FILE" "$CONFIG_FILE"
  exit 0
fi

mapfile -t MONITOR_ROWS < <(hyprctl monitors -j | jq -r '.[] | "\(.name)|\(.width // 1920)"')

if [ "${#MONITOR_ROWS[@]}" -eq 0 ]; then
  cat >"$TMP_FILE" <<'EOF'
monitor = ,preferred,auto,1
EOF
  mv "$TMP_FILE" "$CONFIG_FILE"
  exit 0
fi

{
  printf "# Auto-generated by detect-monitors.sh\n"
  POS_X=0
  for ROW in "${MONITOR_ROWS[@]}"; do
    NAME="${ROW%%|*}"
    WIDTH="${ROW##*|}"
    printf "monitor = %s,preferred,%sx0,1\n" "$NAME" "$POS_X"
    POS_X=$((POS_X + WIDTH))
  done
} >"$TMP_FILE"

mv "$TMP_FILE" "$CONFIG_FILE"
