#!/usr/bin/env bash
set -euo pipefail

CONFIG_FILE="$HOME/.config/hypr/hardware-env.conf"
TMP_FILE="${CONFIG_FILE}.tmp"

mkdir -p "$(dirname "$CONFIG_FILE")"

GPU_INFO=""
if command -v lspci >/dev/null 2>&1; then
  GPU_INFO="$(lspci | grep -Ei 'vga|3d|display' || true)"
fi

{
  printf "# Auto-generated by detect-gpu.sh\n"
  if printf '%s' "$GPU_INFO" | grep -qi nvidia; then
    printf "env = WLR_NO_HARDWARE_CURSORS,1\n"
    printf "env = LIBVA_DRIVER_NAME,nvidia\n"
    printf "env = __GLX_VENDOR_LIBRARY_NAME,nvidia\n"
  fi
} >"$TMP_FILE"

mv "$TMP_FILE" "$CONFIG_FILE"
